name: 'Upstream Sync'

on:
  schedule:
    - cron:  '10 14 * * 5'
  workflow_dispatch:  # click the button on Github repo!
    inputs:
      sync_test_mode: # Adds a boolean option that appears during manual workflow run for easy test mode config
        description: 'Fork Sync Test Mode'
        type: boolean
        default: false

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo
    steps:
    # REQUIRED step
    # Step 1: request upstream releases from github api using fjogeleit/http-request-action
    - name: Obtain latest upstream release tag
      # don't omit the step ID, it's used later to access the api response
      id: upstream_releases
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://api.github.com/repos/brave/brave-browser/releases?page=1&per_page=1"
        method: 'GET'
    # REQUIRED step
    # Step 2: run a standard checkout action, provided by github
    - name: Checkout target repo to upstream release tag ref
      uses: actions/checkout@v3
      with:
        # optional: set the branch to checkout,
        # sync action checks out your 'target_sync_branch' anyway
        ref:  ${{ fromJson(steps.upstream_releases.outputs.response)[0].tag_name }}
        # REQUIRED if your upstream repo is private (see wiki)
        persist-credentials: false

    # REQUIRED step
    # Step 3: run the sync action
    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: master
        # REQUIRED 'target_repo_token' exactly like this!
        target_repo_token: ${{ secrets.UPSTREAM_SYNC_TOKEN }}
        upstream_sync_branch: master
        upstream_sync_repo: brave/brave-browser
        upstream_repo_access_token: ${{ secrets.UPSTREAM_REPO_SECRET }}

        # Set test_mode true during manual dispatch to run tests instead of the true action!!
        test_mode: ${{ inputs.sync_test_mode }}
      
    # Step 4: Display a sample message based on the sync output var 'has_new_commits'
    - name: New commits found
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found to sync."
    
    - name: No new commits
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "There were no new commits."
      
    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}
